version: '3.1'
services:
  mongodb:
    container_name: products-datastore
    image: mongo:3.2
    command: mongod --smallfiles
  web:
    container_name: products-service
    build:
      context: ./
      dockerfile: Dockerfile
    image: products-service-image
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    links:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb/products